name: Call a reusable workflow

on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: mowies/test-actions-build-matrix-handover/.github/workflows/called.yml@main
    with:
      matrix: "{\"config\": \"{\"string\":\"hello\"}, {\"string\":\"world\"}}\"}"
