name: Call a reusable workflow

on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: mowies/test-actions-build-matrix-handover/.github/workflows/called.yml@master
    with:
      matrix: "\"config\": \"{\"string\":\"hello\"}, {\"string\":\"world\"}}\""
